Source.cpp
int getData()
References printMsg.
Referenced by main.
int findNumDigits(int n)
Referenced by processMenuChoice.
int findDigitAtPosition(int n, int p)
Referenced by processMenuChoice.
void displayMenu(int &c)
Referenced by main.
void processMenuChoice(int c, int &n)
References displayAdditionTable, displayMultiplicationTable, findDigitAtPosition, findNumDigits, isOddEven, isPosNeg, printMsg.
Referenced by main.
void isPosNeg(int n)
References printMsg.
Referenced by processMenuChoice.
void isOddEven(int n)
References printMsg.
Referenced by processMenuChoice.
void displayAdditionTable()
Referenced by processMenuChoice.
void displayMultiplicationTable()
Referenced by processMenuChoice.
void printMsg(string msg, double n=0, bool var=false)
Referenced by getData, isOddEven, isPosNeg, main, processMenuChoice.
int main()
References displayMenu, getData, printMsg, processMenuChoice.